# Sample Data Creation Script

## Descriptions

![Data Sampling Requirements](./figs/data_sampling_requirements.png)
![Data Sampling Flow](./figs/data_sampling_flow.png)

## Imports

In [2]:
import numpy as np
import pandas as pd

from k_anonymization import datasets

## Data Creation

### Original Data

In [3]:
DATASET = datasets.ADULT
org_df = DATASET.df
org_df.shape[0]

30162

### Unique-QIDs Data

In [4]:
freq_org_df = org_df.groupby(DATASET.qids, as_index=False).count()
org_unique_indices = freq_org_df[freq_org_df[DATASET.target] == 1].index

In [5]:
org_unique_df = pd.merge(
    org_df.reset_index(),
    freq_org_df[freq_org_df[DATASET.target] == 1][DATASET.qids],
    on=DATASET.qids,
    how="right",
)
org_unique_df

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
0,3307,Female,17,Amer-Indian-Eskimo,Never-married,10th,United-States,Private,Other-service,<=50K
1,13628,Female,17,Amer-Indian-Eskimo,Never-married,11th,United-States,Private,Other-service,<=50K
2,1357,Female,17,Asian-Pac-Islander,Never-married,11th,United-States,Private,Adm-clerical,<=50K
3,18068,Female,17,Black,Never-married,10th,United-States,Private,Other-service,<=50K
4,24901,Female,17,Black,Never-married,11th,United-States,Federal-gov,Adm-clerical,<=50K
...,...,...,...,...,...,...,...,...,...,...
14016,9435,Male,90,White,Married-civ-spouse,Some-college,United-States,Self-emp-not-inc,Farming-fishing,<=50K
14017,3734,Male,90,White,Never-married,11th,United-States,Private,Handlers-cleaners,<=50K
14018,11093,Male,90,White,Never-married,Bachelors,United-States,Private,Exec-managerial,<=50K
14019,22283,Male,90,White,Never-married,HS-grad,United-States,Self-emp-not-inc,Exec-managerial,<=50K
14020,14226,Male,90,White,Widowed,HS-grad,United-States,Private,Transport-moving,<=50K

#### Unique-QIDs Data, Target = "$\tiny\leq$50K"

In [6]:
org_unique_df_A = org_unique_df[
    org_unique_df[DATASET.target] == org_unique_df.loc[0, DATASET.target]
]
org_unique_df_A

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
0,3307,Female,17,Amer-Indian-Eskimo,Never-married,10th,United-States,Private,Other-service,<=50K
1,13628,Female,17,Amer-Indian-Eskimo,Never-married,11th,United-States,Private,Other-service,<=50K
2,1357,Female,17,Asian-Pac-Islander,Never-married,11th,United-States,Private,Adm-clerical,<=50K
3,18068,Female,17,Black,Never-married,10th,United-States,Private,Other-service,<=50K
4,24901,Female,17,Black,Never-married,11th,United-States,Federal-gov,Adm-clerical,<=50K
...,...,...,...,...,...,...,...,...,...,...
14016,9435,Male,90,White,Married-civ-spouse,Some-college,United-States,Self-emp-not-inc,Farming-fishing,<=50K
14017,3734,Male,90,White,Never-married,11th,United-States,Private,Handlers-cleaners,<=50K
14018,11093,Male,90,White,Never-married,Bachelors,United-States,Private,Exec-managerial,<=50K
14019,22283,Male,90,White,Never-married,HS-grad,United-States,Self-emp-not-inc,Exec-managerial,<=50K
14020,14226,Male,90,White,Widowed,HS-grad,United-States,Private,Transport-moving,<=50K

#### Unique-QIDs Data, Target = ">50K"

In [7]:
org_unique_df_B = org_unique_df[
    org_unique_df[DATASET.target] != org_unique_df.loc[0, DATASET.target]
]
org_unique_df_B

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
211,5158,Female,21,Amer-Indian-Eskimo,Married-civ-spouse,Assoc-acdm,United-States,Private,Adm-clerical,>50K
229,10132,Female,21,Black,Never-married,Some-college,United-States,Private,Protective-serv,>50K
278,22597,Female,22,Amer-Indian-Eskimo,Never-married,Bachelors,United-States,Private,Prof-specialty,>50K
313,27697,Female,22,White,Married-AF-spouse,Some-college,United-States,Private,Other-service,>50K
342,1678,Female,22,White,Never-married,HS-grad,Dominican-Republic,Self-emp-not-inc,Prof-specialty,>50K
...,...,...,...,...,...,...,...,...,...,...
14003,4953,Male,90,Black,Never-married,Masters,United-States,Private,Exec-managerial,>50K
14009,8287,Male,90,White,Married-civ-spouse,Bachelors,United-States,Private,Sales,>50K
14011,9749,Male,90,White,Married-civ-spouse,HS-grad,Ecuador,Private,Craft-repair,>50K
14014,4921,Male,90,White,Married-civ-spouse,Masters,United-States,Local-gov,Exec-managerial,>50K
14015,8132,Male,90,White,Married-civ-spouse,Prof-school,United-States,Private,Prof-specialty,>50K

### * Sample Data

Use a seed for reproducibility

In [8]:
SEED = 202512

In [9]:
sample_A = org_unique_df_A.sample(n=1500, random_state=SEED)
sample_B = org_unique_df_B.sample(n=1500, random_state=SEED)
sample = pd.concat([sample_A, sample_B], axis=0).sample(frac=1, random_state=SEED)
sample

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
13418,17207,Male,64,Asian-Pac-Islander,Married-civ-spouse,Assoc-acdm,United-States,Federal-gov,Other-service,>50K
7477,2307,Male,31,Asian-Pac-Islander,Married-civ-spouse,Assoc-acdm,United-States,Private,Craft-repair,>50K
11558,11823,Male,50,Asian-Pac-Islander,Married-civ-spouse,HS-grad,South,Private,Prof-specialty,>50K
9353,6647,Male,39,White,Divorced,Bachelors,Mexico,State-gov,Protective-serv,>50K
4915,8704,Female,62,White,Married-civ-spouse,Bachelors,United-States,Private,Adm-clerical,>50K
...,...,...,...,...,...,...,...,...,...,...
3205,19401,Female,44,Black,Separated,Some-college,United-States,Private,Prof-specialty,<=50K
9329,21123,Male,39,Black,Married-civ-spouse,HS-grad,United-States,Private,Transport-moving,>50K
896,4005,Female,27,White,Married-civ-spouse,Some-college,United-States,Private,Exec-managerial,>50K
2469,8468,Female,38,White,Widowed,Some-college,United-States,Private,Exec-managerial,>50K
3678,1646,Female,47,White,Never-married,9th,United-States,Private,Other-service,<=50K

### * Validation Data

In [10]:
unsampled_A = org_unique_df_A[~org_unique_df_A.index.isin(sample_A.index)]
unsampled_B = org_unique_df_B[~org_unique_df_B.index.isin(sample_B.index)]

In [11]:
predict_org_A = unsampled_A.sample(n=300, random_state=SEED)
predict_org_B = unsampled_B.sample(n=300, random_state=SEED)
predict_org = pd.concat([predict_org_A, predict_org_B], axis=0).sample(
    frac=1, random_state=SEED
)
predict_org

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
5292,13519,Female,80,White,Widowed,Some-college,United-States,Private,Adm-clerical,<=50K
13659,28902,Male,67,White,Married-civ-spouse,Some-college,United-States,State-gov,Protective-serv,>50K
5652,15774,Male,21,White,Never-married,9th,United-States,Private,Transport-moving,<=50K
10839,14679,Male,46,Black,Married-civ-spouse,Masters,United-States,Local-gov,Prof-specialty,>50K
9664,11672,Male,40,White,Never-married,1st-4th,El-Salvador,Private,Other-service,<=50K
...,...,...,...,...,...,...,...,...,...,...
2935,4930,Female,42,Black,Married-civ-spouse,Bachelors,United-States,Private,Exec-managerial,>50K
3097,9939,Female,43,White,Divorced,HS-grad,United-States,State-gov,Adm-clerical,>50K
3090,13175,Female,43,White,Divorced,Bachelors,United-States,Private,Prof-specialty,>50K
2427,924,Female,38,White,Married-civ-spouse,HS-grad,United-States,State-gov,Prof-specialty,>50K
1609,18663,Female,32,White,Never-married,Bachelors,United-States,Local-gov,Prof-specialty,<=50K

## Save Data

In [12]:
import os

BASE_PATH = f"./results/{DATASET.name.replace(" ", "_")}"
os.makedirs(f"{BASE_PATH}/sample", exist_ok=True)

In [15]:
sample.to_csv(f"{BASE_PATH}/sample/data.csv", index=False)

In [14]:
predict_org[org_df.columns].to_csv(f"{BASE_PATH}/predict_org.csv", index=False)