# Sample Data Creation Script

![Data Sampling Requirements](./figs/data_sampling_requirements.png)
![Data Sampling Flow](./figs/data_sampling_flow.png)

## Imports

In [1]:
import numpy as np
import pandas as pd

from k_anonymization import datasets

## Data Creation

### Original Data

In [2]:
DATASET = datasets.ADULT
org_df = DATASET.df
org_df.shape[0]

30162

### Unique-QIDs Data

In [3]:
freq_org_df = org_df.groupby(DATASET.qids, as_index=False).count()
org_unique_indices = freq_org_df[freq_org_df[DATASET.target] == 1].index

In [4]:
org_unique_df = pd.merge(
    org_df.reset_index(),
    freq_org_df[freq_org_df[DATASET.target] == 1][DATASET.qids],
    on=DATASET.qids,
    how="right",
)
org_unique_df

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
0,3307,Female,17,Amer-Indian-Eskimo,Never-married,10th,United-States,Private,Other-service,<=50K
1,13628,Female,17,Amer-Indian-Eskimo,Never-married,11th,United-States,Private,Other-service,<=50K
2,1357,Female,17,Asian-Pac-Islander,Never-married,11th,United-States,Private,Adm-clerical,<=50K
3,18068,Female,17,Black,Never-married,10th,United-States,Private,Other-service,<=50K
4,24901,Female,17,Black,Never-married,11th,United-States,Federal-gov,Adm-clerical,<=50K
...,...,...,...,...,...,...,...,...,...,...
14016,9435,Male,90,White,Married-civ-spouse,Some-college,United-States,Self-emp-not-inc,Farming-fishing,<=50K
14017,3734,Male,90,White,Never-married,11th,United-States,Private,Handlers-cleaners,<=50K
14018,11093,Male,90,White,Never-married,Bachelors,United-States,Private,Exec-managerial,<=50K
14019,22283,Male,90,White,Never-married,HS-grad,United-States,Self-emp-not-inc,Exec-managerial,<=50K
14020,14226,Male,90,White,Widowed,HS-grad,United-States,Private,Transport-moving,<=50K

#### Unique-QIDs Data, Target = "$\tiny\leq$50K"

In [5]:
org_unique_df_A = org_unique_df[
    org_unique_df[DATASET.target] == org_unique_df.loc[0, DATASET.target]
]
org_unique_df_A

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
0,3307,Female,17,Amer-Indian-Eskimo,Never-married,10th,United-States,Private,Other-service,<=50K
1,13628,Female,17,Amer-Indian-Eskimo,Never-married,11th,United-States,Private,Other-service,<=50K
2,1357,Female,17,Asian-Pac-Islander,Never-married,11th,United-States,Private,Adm-clerical,<=50K
3,18068,Female,17,Black,Never-married,10th,United-States,Private,Other-service,<=50K
4,24901,Female,17,Black,Never-married,11th,United-States,Federal-gov,Adm-clerical,<=50K
...,...,...,...,...,...,...,...,...,...,...
14016,9435,Male,90,White,Married-civ-spouse,Some-college,United-States,Self-emp-not-inc,Farming-fishing,<=50K
14017,3734,Male,90,White,Never-married,11th,United-States,Private,Handlers-cleaners,<=50K
14018,11093,Male,90,White,Never-married,Bachelors,United-States,Private,Exec-managerial,<=50K
14019,22283,Male,90,White,Never-married,HS-grad,United-States,Self-emp-not-inc,Exec-managerial,<=50K
14020,14226,Male,90,White,Widowed,HS-grad,United-States,Private,Transport-moving,<=50K

#### Unique-QIDs Data, Target = ">50K"

In [6]:
org_unique_df_B = org_unique_df[
    org_unique_df[DATASET.target] != org_unique_df.loc[0, DATASET.target]
]
org_unique_df_B

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
211,5158,Female,21,Amer-Indian-Eskimo,Married-civ-spouse,Assoc-acdm,United-States,Private,Adm-clerical,>50K
229,10132,Female,21,Black,Never-married,Some-college,United-States,Private,Protective-serv,>50K
278,22597,Female,22,Amer-Indian-Eskimo,Never-married,Bachelors,United-States,Private,Prof-specialty,>50K
313,27697,Female,22,White,Married-AF-spouse,Some-college,United-States,Private,Other-service,>50K
342,1678,Female,22,White,Never-married,HS-grad,Dominican-Republic,Self-emp-not-inc,Prof-specialty,>50K
...,...,...,...,...,...,...,...,...,...,...
14003,4953,Male,90,Black,Never-married,Masters,United-States,Private,Exec-managerial,>50K
14009,8287,Male,90,White,Married-civ-spouse,Bachelors,United-States,Private,Sales,>50K
14011,9749,Male,90,White,Married-civ-spouse,HS-grad,Ecuador,Private,Craft-repair,>50K
14014,4921,Male,90,White,Married-civ-spouse,Masters,United-States,Local-gov,Exec-managerial,>50K
14015,8132,Male,90,White,Married-civ-spouse,Prof-school,United-States,Private,Prof-specialty,>50K

### * Sample Data

Use a seed for reproducibility

In [7]:
SEED = 202602

In [8]:
sample_A = org_unique_df_A.sample(n=1500, random_state=SEED)
sample_B = org_unique_df_B.sample(n=1500, random_state=SEED)
sample = pd.concat([sample_A, sample_B], axis=0).sample(frac=1, random_state=SEED)
sample

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
6248,26256,Male,25,White,Married-civ-spouse,Bachelors,United-States,State-gov,Protective-serv,>50K
2718,24158,Female,40,White,Married-civ-spouse,Some-college,United-States,Private,Exec-managerial,>50K
11814,17103,Male,51,White,Married-civ-spouse,Bachelors,United-States,Federal-gov,Exec-managerial,<=50K
12859,23949,Male,58,White,Married-civ-spouse,Masters,United-States,Private,Exec-managerial,>50K
3237,15231,Female,44,White,Divorced,Masters,United-States,Self-emp-not-inc,Exec-managerial,<=50K
...,...,...,...,...,...,...,...,...,...,...
4349,23069,Female,54,White,Divorced,Assoc-acdm,United-States,Private,Exec-managerial,>50K
4417,25835,Female,55,Asian-Pac-Islander,Never-married,Masters,Thailand,Private,Prof-specialty,<=50K
13593,27408,Male,66,White,Married-civ-spouse,HS-grad,United-States,Local-gov,Exec-managerial,<=50K
7111,24916,Male,29,White,Married-civ-spouse,Bachelors,Germany,Local-gov,Prof-specialty,>50K
3973,25544,Female,50,White,Divorced,11th,United-States,Private,Other-service,<=50K

### * Validation Data

In [9]:
unsampled_A = org_unique_df_A[~org_unique_df_A.index.isin(sample_A.index)]
unsampled_B = org_unique_df_B[~org_unique_df_B.index.isin(sample_B.index)]

In [10]:
predict_org_A = unsampled_A.sample(n=300, random_state=SEED)
predict_org_B = unsampled_B.sample(n=300, random_state=SEED)
predict_org = pd.concat([predict_org_A, predict_org_B], axis=0).sample(
    frac=1, random_state=SEED
)
predict_org

,index,sex,age,race,marital-status,education,native-country,workclass,occupation,salary-class
5706,992,Male,22,Asian-Pac-Islander,Never-married,Bachelors,Taiwan,Private,Sales,<=50K
3571,24983,Female,46,White,Widowed,HS-grad,United-States,Private,Adm-clerical,<=50K
12518,11119,Male,56,White,Married-civ-spouse,10th,Cuba,Private,Other-service,>50K
11601,17015,Male,50,White,Divorced,Doctorate,United-States,Private,Prof-specialty,>50K
13635,17090,Male,67,White,Married-civ-spouse,HS-grad,United-States,Federal-gov,Tech-support,>50K
...,...,...,...,...,...,...,...,...,...,...
2065,15304,Female,36,Asian-Pac-Islander,Widowed,HS-grad,United-States,Private,Other-service,<=50K
7927,6283,Male,32,White,Never-married,Some-college,United-States,State-gov,Adm-clerical,<=50K
13841,13186,Male,72,White,Married-civ-spouse,Prof-school,United-States,Self-emp-inc,Prof-specialty,>50K
11784,15726,Male,51,White,Married-civ-spouse,12th,United-States,Private,Craft-repair,<=50K
13743,1352,Male,69,White,Married-civ-spouse,Masters,United-States,State-gov,Prof-specialty,<=50K

## Save Data

In [11]:
import os

BASE_PATH = f"./results/{DATASET.name.replace(" ", "_")}"
os.makedirs(f"{BASE_PATH}/sample", exist_ok=True)

In [12]:
sample.to_csv(f"{BASE_PATH}/sample/data.csv", index=False)

In [13]:
predict_org[org_df.columns].to_csv(f"{BASE_PATH}/predict_org.csv", index=False)